version: '3'
services:
    #MySQL Service
    database:
        image: mysql:8.0
        container_name: db3
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: password
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge
